name: mimic2openehr_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - jupyter
  - pandas
  - numpy
  - matplotlib
  - psycopg2
  - sqlalchemy
  - scp
  - paramiko
  - pytorch
  - requests
  - regex
